[database]
host = "localhost"
port = 5433
user = "gts"
password = "gts"
name = "gts"
max_connections = 10

[server]
host = "0.0.0.0"
port = 8080

[auth]
session_secret = "dev-only-session-secret-change-me-please-0123456789abcdef"
superadmin_username = "admin"
superadmin_password = "admin"
