//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "address")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    #[serde(default)]
    pub postal_index: String,
    #[sea_orm(column_type = "Text")]
    #[serde(default)]
    pub district: String,
    #[sea_orm(column_type = "Text")]
    #[serde(default)]
    pub street: String,
    #[sea_orm(column_type = "Text")]
    #[serde(default)]
    pub house: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub apartment: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::installation_queue::Entity")]
    InstallationQueue,
    #[sea_orm(has_many = "super::pbx::Entity")]
    Pbx,
    #[sea_orm(has_many = "super::phone_number::Entity")]
    PhoneNumber,
    #[sea_orm(has_many = "super::public_phone::Entity")]
    PublicPhone,
    #[sea_orm(has_many = "super::subscriber::Entity")]
    Subscriber,
}

impl Related<super::installation_queue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InstallationQueue.def()
    }
}

impl Related<super::pbx::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pbx.def()
    }
}

impl Related<super::phone_number::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PhoneNumber.def()
    }
}

impl Related<super::public_phone::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PublicPhone.def()
    }
}

impl Related<super::subscriber::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subscriber.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
