//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "app_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i64,
    #[sea_orm(column_type = "Text", unique)]
    #[serde(default)]
    pub username: String,
    #[sea_orm(column_type = "Text")]
    #[serde(default)]
    pub password_hash: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub full_name: Option<String>,
    #[serde(default)]
    pub is_superadmin: bool,
    #[serde(default)]
    pub is_active: bool,
    #[serde(default = "crate::serde_defaults::now_tz")]
    pub created_at: DateTimeWithTimeZone,
    pub last_login_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user_role::Entity")]
    UserRole,
}

impl Related<super::user_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRole.def()
    }
}

impl Related<super::role::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_role::Relation::Role.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_role::Relation::AppUser.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
