//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "billing_settings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(skip_deserializing)]
    pub id: i16,
    #[sea_orm(column_type = "Decimal(Some((4, 3)))")]
    #[serde(default)]
    pub privilege_discount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((12, 2)))")]
    #[serde(default)]
    pub reconnection_fee: Decimal,
    #[sea_orm(column_type = "Decimal(Some((6, 5)))")]
    #[serde(default)]
    pub penalty_daily_rate: Decimal,
    #[serde(default)]
    pub payment_due_day: i16,
    #[serde(default)]
    pub notice_grace_days: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
