//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::CallType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "call_record")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i64,
    #[serde(default)]
    pub from_number_id: i64,
    #[serde(default)]
    pub call_type: CallType,
    pub dest_city_id: Option<i64>,
    pub dest_number_id: Option<i64>,
    #[serde(default = "crate::serde_defaults::now_tz")]
    pub started_at: DateTimeWithTimeZone,
    #[serde(default)]
    pub duration_sec: i32,
    #[sea_orm(column_type = "Decimal(Some((12, 2)))")]
    #[serde(default)]
    pub cost: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::city::Entity",
        from = "Column::DestCityId",
        to = "super::city::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    City,
    #[sea_orm(
        belongs_to = "super::phone_number::Entity",
        from = "Column::DestNumberId",
        to = "super::phone_number::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    PhoneNumber2,
    #[sea_orm(
        belongs_to = "super::phone_number::Entity",
        from = "Column::FromNumberId",
        to = "super::phone_number::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    PhoneNumber1,
}

impl Related<super::city::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::City.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
