//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "city")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i64,
    #[sea_orm(column_type = "Text", unique)]
    #[serde(default)]
    pub name: String,
    #[sea_orm(unique)]
    #[serde(default)]
    pub is_home: bool,
    #[serde(default = "crate::serde_defaults::now_tz")]
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::call_record::Entity")]
    CallRecord,
}

impl Related<super::call_record::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CallRecord.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
