//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::QueueStatus;
use super::sea_orm_active_enums::QueueType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "installation_queue")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    #[serde(default)]
    pub applicant_last_name: String,
    #[sea_orm(column_type = "Text")]
    #[serde(default)]
    pub applicant_first_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub applicant_middle_name: Option<String>,
    #[serde(default)]
    pub queue_type: QueueType,
    #[serde(default)]
    pub address_id: i64,
    pub desired_pbx_id: Option<i64>,
    #[serde(default = "crate::serde_defaults::today")]
    pub requested_at: Date,
    #[serde(default)]
    pub status: QueueStatus,
    pub assigned_number_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub note: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::address::Entity",
        from = "Column::AddressId",
        to = "super::address::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Address,
    #[sea_orm(
        belongs_to = "super::pbx::Entity",
        from = "Column::DesiredPbxId",
        to = "super::pbx::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Pbx,
    #[sea_orm(
        belongs_to = "super::phone_number::Entity",
        from = "Column::AssignedNumberId",
        to = "super::phone_number::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    PhoneNumber,
}

impl Related<super::address::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Address.def()
    }
}

impl Related<super::pbx::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pbx.def()
    }
}

impl Related<super::phone_number::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PhoneNumber.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
