//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::InvoiceKind;
use super::sea_orm_active_enums::InvoiceStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "invoice")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i64,
    #[serde(default)]
    pub subscriber_id: i64,
    #[serde(default)]
    pub kind: InvoiceKind,
    #[serde(default)]
    pub period_year: i16,
    #[serde(default)]
    pub period_month: i16,
    #[sea_orm(column_type = "Decimal(Some((12, 2)))")]
    #[serde(default)]
    pub amount: Decimal,
    #[serde(default = "crate::serde_defaults::today")]
    pub due_date: Date,
    #[serde(default)]
    pub status: InvoiceStatus,
    #[serde(default = "crate::serde_defaults::now_tz")]
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::payment::Entity")]
    Payment,
    #[sea_orm(has_many = "super::penalty::Entity")]
    Penalty,
    #[sea_orm(
        belongs_to = "super::subscriber::Entity",
        from = "Column::SubscriberId",
        to = "super::subscriber::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Subscriber,
}

impl Related<super::payment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Payment.def()
    }
}

impl Related<super::penalty::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Penalty.def()
    }
}

impl Related<super::subscriber::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subscriber.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
