//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod serde_defaults;

pub mod prelude;

pub mod address;
pub mod app_user;
pub mod billing_settings;
pub mod call_record;
pub mod city;
pub mod installation_queue;
pub mod invoice;
pub mod notification;
pub mod payment;
pub mod pbx;
pub mod pbx_city;
pub mod pbx_department;
pub mod pbx_institution;
pub mod penalty;
pub mod permission;
pub mod phone_number;
pub mod public_phone;
pub mod role;
pub mod role_permission;
pub mod sea_orm_active_enums;
pub mod subscriber;
pub mod tariff;
pub mod user_role;
