//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::NotificationKind;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "notification")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i64,
    #[serde(default)]
    pub subscriber_id: i64,
    #[serde(default)]
    pub kind: NotificationKind,
    #[serde(default = "crate::serde_defaults::today")]
    pub sent_at: Date,
    #[serde(default = "crate::serde_defaults::today")]
    pub deadline: Date,
    #[serde(default)]
    pub resolved: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::subscriber::Entity",
        from = "Column::SubscriberId",
        to = "super::subscriber::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Subscriber,
}

impl Related<super::subscriber::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subscriber.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
