//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::PbxType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "pbx")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i64,
    #[sea_orm(column_type = "Text", unique)]
    #[serde(default)]
    pub name: String,
    #[sea_orm(column_type = "Text", unique)]
    #[serde(default)]
    pub code: String,
    #[serde(default)]
    pub pbx_type: PbxType,
    #[sea_orm(column_type = "Text")]
    #[serde(default)]
    pub district: String,
    pub address_id: Option<i64>,
    #[serde(default)]
    pub capacity_numbers: i32,
    #[serde(default)]
    pub total_channels: i32,
    #[serde(default)]
    pub free_channels: i32,
    #[serde(default)]
    pub has_free_cable: bool,
    #[serde(default = "crate::serde_defaults::now_tz")]
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::address::Entity",
        from = "Column::AddressId",
        to = "super::address::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Address,
    #[sea_orm(has_many = "super::installation_queue::Entity")]
    InstallationQueue,
    #[sea_orm(has_one = "super::pbx_city::Entity")]
    PbxCity,
    #[sea_orm(has_one = "super::pbx_department::Entity")]
    PbxDepartment,
    #[sea_orm(has_one = "super::pbx_institution::Entity")]
    PbxInstitution,
    #[sea_orm(has_many = "super::phone_number::Entity")]
    PhoneNumber,
    #[sea_orm(has_many = "super::public_phone::Entity")]
    PublicPhone,
}

impl Related<super::address::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Address.def()
    }
}

impl Related<super::installation_queue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InstallationQueue.def()
    }
}

impl Related<super::pbx_city::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PbxCity.def()
    }
}

impl Related<super::pbx_department::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PbxDepartment.def()
    }
}

impl Related<super::pbx_institution::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PbxInstitution.def()
    }
}

impl Related<super::phone_number::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PhoneNumber.def()
    }
}

impl Related<super::public_phone::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PublicPhone.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
