//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "pbx_institution")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(default)]
    pub pbx_id: i64,
    #[sea_orm(column_type = "Text")]
    #[serde(default)]
    pub institution_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub parent_department: Option<String>,
    #[serde(default)]
    pub closed_network: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::pbx::Entity",
        from = "Column::PbxId",
        to = "super::pbx::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Pbx,
}

impl Related<super::pbx::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pbx.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
