//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "penalty")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i64,
    #[serde(default)]
    pub subscriber_id: i64,
    pub invoice_id: Option<i64>,
    #[sea_orm(column_type = "Decimal(Some((12, 2)))")]
    #[serde(default)]
    pub amount: Decimal,
    #[sea_orm(column_type = "Text", nullable)]
    pub reason: Option<String>,
    #[serde(default = "crate::serde_defaults::today")]
    pub accrued_at: Date,
    #[serde(default)]
    pub paid: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::invoice::Entity",
        from = "Column::InvoiceId",
        to = "super::invoice::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Invoice,
    #[sea_orm(
        belongs_to = "super::subscriber::Entity",
        from = "Column::SubscriberId",
        to = "super::subscriber::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Subscriber,
}

impl Related<super::invoice::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Invoice.def()
    }
}

impl Related<super::subscriber::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subscriber.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
