//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::IntercityStatus;
use super::sea_orm_active_enums::LineType;
use super::sea_orm_active_enums::NumberStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "phone_number")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i64,
    #[sea_orm(column_type = "Text", unique)]
    #[serde(default)]
    pub number: String,
    #[serde(default)]
    pub pbx_id: i64,
    #[serde(default)]
    pub line_type: LineType,
    #[serde(default)]
    pub intercity: IntercityStatus,
    #[serde(default)]
    pub status: NumberStatus,
    pub address_id: Option<i64>,
    #[serde(default = "crate::serde_defaults::now_tz")]
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::address::Entity",
        from = "Column::AddressId",
        to = "super::address::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Address,
    #[sea_orm(has_many = "super::installation_queue::Entity")]
    InstallationQueue,
    #[sea_orm(
        belongs_to = "super::pbx::Entity",
        from = "Column::PbxId",
        to = "super::pbx::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Pbx,
    #[sea_orm(has_many = "super::public_phone::Entity")]
    PublicPhone,
    #[sea_orm(has_many = "super::subscriber::Entity")]
    Subscriber,
}

impl Related<super::address::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Address.def()
    }
}

impl Related<super::installation_queue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InstallationQueue.def()
    }
}

impl Related<super::pbx::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pbx.def()
    }
}

impl Related<super::public_phone::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PublicPhone.def()
    }
}

impl Related<super::subscriber::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subscriber.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
