//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::address::Entity as Address;
pub use super::app_user::Entity as AppUser;
pub use super::billing_settings::Entity as BillingSettings;
pub use super::call_record::Entity as CallRecord;
pub use super::city::Entity as City;
pub use super::installation_queue::Entity as InstallationQueue;
pub use super::invoice::Entity as Invoice;
pub use super::notification::Entity as Notification;
pub use super::payment::Entity as Payment;
pub use super::pbx::Entity as Pbx;
pub use super::pbx_city::Entity as PbxCity;
pub use super::pbx_department::Entity as PbxDepartment;
pub use super::pbx_institution::Entity as PbxInstitution;
pub use super::penalty::Entity as Penalty;
pub use super::permission::Entity as Permission;
pub use super::phone_number::Entity as PhoneNumber;
pub use super::public_phone::Entity as PublicPhone;
pub use super::role::Entity as Role;
pub use super::role_permission::Entity as RolePermission;
pub use super::subscriber::Entity as Subscriber;
pub use super::tariff::Entity as Tariff;
pub use super::user_role::Entity as UserRole;
