//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::PublicPhoneKind;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "public_phone")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i64,
    #[serde(default)]
    pub kind: PublicPhoneKind,
    #[serde(default)]
    pub pbx_id: i64,
    #[serde(default)]
    pub address_id: i64,
    pub phone_number_id: Option<i64>,
    #[serde(default = "crate::serde_defaults::today")]
    pub installed_at: Date,
    #[serde(default)]
    pub active: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::address::Entity",
        from = "Column::AddressId",
        to = "super::address::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Address,
    #[sea_orm(
        belongs_to = "super::pbx::Entity",
        from = "Column::PbxId",
        to = "super::pbx::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Pbx,
    #[sea_orm(
        belongs_to = "super::phone_number::Entity",
        from = "Column::PhoneNumberId",
        to = "super::phone_number::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    PhoneNumber,
}

impl Related<super::address::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Address.def()
    }
}

impl Related<super::pbx::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pbx.def()
    }
}

impl Related<super::phone_number::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PhoneNumber.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
