//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "call_type")]
pub enum CallType {
    #[default]
    #[sea_orm(string_value = "local")]
    Local,
    #[sea_orm(string_value = "internal")]
    Internal,
    #[sea_orm(string_value = "external")]
    External,
    #[sea_orm(string_value = "intercity")]
    Intercity,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "gender")]
pub enum Gender {
    #[default]
    #[sea_orm(string_value = "male")]
    Male,
    #[sea_orm(string_value = "female")]
    Female,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "intercity_status")]
pub enum IntercityStatus {
    #[default]
    #[sea_orm(string_value = "none")]
    None,
    #[sea_orm(string_value = "open")]
    Open,
    #[sea_orm(string_value = "closed")]
    Closed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "invoice_kind")]
pub enum InvoiceKind {
    #[default]
    #[sea_orm(string_value = "subscription")]
    Subscription,
    #[sea_orm(string_value = "intercity")]
    Intercity,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "invoice_status")]
pub enum InvoiceStatus {
    #[default]
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "paid")]
    Paid,
    #[sea_orm(string_value = "overdue")]
    Overdue,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "line_type")]
pub enum LineType {
    #[default]
    #[sea_orm(string_value = "main")]
    Main,
    #[sea_orm(string_value = "parallel")]
    Parallel,
    #[sea_orm(string_value = "paired")]
    Paired,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "notification_kind")]
pub enum NotificationKind {
    #[default]
    #[sea_orm(string_value = "subscription_debt")]
    SubscriptionDebt,
    #[sea_orm(string_value = "intercity_debt")]
    IntercityDebt,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "number_status")]
pub enum NumberStatus {
    #[default]
    #[sea_orm(string_value = "free")]
    Free,
    #[sea_orm(string_value = "reserved")]
    Reserved,
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "blocked")]
    Blocked,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "pbx_type")]
pub enum PbxType {
    #[default]
    #[sea_orm(string_value = "city")]
    City,
    #[sea_orm(string_value = "departmental")]
    Departmental,
    #[sea_orm(string_value = "institutional")]
    Institutional,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "privilege_kind")]
pub enum PrivilegeKind {
    #[default]
    #[sea_orm(string_value = "pensioner")]
    Pensioner,
    #[sea_orm(string_value = "disabled")]
    Disabled,
    #[sea_orm(string_value = "veteran")]
    Veteran,
    #[sea_orm(string_value = "other")]
    Other,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "public_phone_kind")]
pub enum PublicPhoneKind {
    #[default]
    #[sea_orm(string_value = "public")]
    Public,
    #[sea_orm(string_value = "payphone")]
    Payphone,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "queue_status")]
pub enum QueueStatus {
    #[default]
    #[sea_orm(string_value = "waiting")]
    Waiting,
    #[sea_orm(string_value = "feasible")]
    Feasible,
    #[sea_orm(string_value = "installed")]
    Installed,
    #[sea_orm(string_value = "rejected")]
    Rejected,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "queue_type")]
pub enum QueueType {
    #[default]
    #[sea_orm(string_value = "regular")]
    Regular,
    #[sea_orm(string_value = "privileged")]
    Privileged,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "subscriber_category"
)]
pub enum SubscriberCategory {
    #[default]
    #[sea_orm(string_value = "regular")]
    Regular,
    #[sea_orm(string_value = "privileged")]
    Privileged,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "subscriber_status")]
pub enum SubscriberStatus {
    #[default]
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "intercity_blocked")]
    IntercityBlocked,
    #[sea_orm(string_value = "disconnected")]
    Disconnected,
}
