//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::Gender;
use super::sea_orm_active_enums::PrivilegeKind;
use super::sea_orm_active_enums::SubscriberCategory;
use super::sea_orm_active_enums::SubscriberStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "subscriber")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    #[serde(default)]
    pub last_name: String,
    #[sea_orm(column_type = "Text")]
    #[serde(default)]
    pub first_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub middle_name: Option<String>,
    #[serde(default)]
    pub gender: Gender,
    #[serde(default = "crate::serde_defaults::today")]
    pub birth_date: Date,
    #[serde(default)]
    pub category: SubscriberCategory,
    pub privilege: Option<PrivilegeKind>,
    #[serde(default)]
    pub status: SubscriberStatus,
    #[serde(default)]
    pub phone_number_id: i64,
    #[serde(default)]
    pub address_id: i64,
    #[serde(default = "crate::serde_defaults::today")]
    pub connected_at: Date,
    pub disconnected_at: Option<Date>,
    #[serde(default = "crate::serde_defaults::now_tz")]
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::address::Entity",
        from = "Column::AddressId",
        to = "super::address::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Address,
    #[sea_orm(has_many = "super::invoice::Entity")]
    Invoice,
    #[sea_orm(has_many = "super::notification::Entity")]
    Notification,
    #[sea_orm(has_many = "super::payment::Entity")]
    Payment,
    #[sea_orm(has_many = "super::penalty::Entity")]
    Penalty,
    #[sea_orm(
        belongs_to = "super::phone_number::Entity",
        from = "Column::PhoneNumberId",
        to = "super::phone_number::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    PhoneNumber,
}

impl Related<super::address::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Address.def()
    }
}

impl Related<super::invoice::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Invoice.def()
    }
}

impl Related<super::notification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notification.def()
    }
}

impl Related<super::payment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Payment.def()
    }
}

impl Related<super::penalty::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Penalty.def()
    }
}

impl Related<super::phone_number::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PhoneNumber.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
