//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::LineType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tariff")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i64,
    #[serde(default)]
    pub line_type: LineType,
    #[serde(default)]
    pub with_intercity: bool,
    #[sea_orm(column_type = "Decimal(Some((12, 2)))")]
    #[serde(default)]
    pub monthly_fee: Decimal,
    #[serde(default = "crate::serde_defaults::today")]
    pub valid_from: Date,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
